import React, {useEffect, useRef, useState} from 'react';
import {api} from './api';
import './constellation.css';

// Generic perspective renderer: content and relationships come from the caller.
export function SpatialScene({nodes, onSelect}) {
  const canvas = useRef(null), scene = useRef({yaw:.2,pitch:.22,zoom:1,targetYaw:.2,targetPitch:.22,targetZoom:1,focus:[0,0,0],targetFocus:[0,0,0],active:null,hover:null,points:[],pointers:new Map(),expanded:true});
  const [expanded,setExpanded]=useState(true);
  const [activeId,setActiveId]=useState('');
  const reset=()=>{Object.assign(scene.current,{targetYaw:.2,targetPitch:.22,targetZoom:1,targetFocus:[0,0,0],active:null,expanded:true});setActiveId('');setExpanded(true);onSelect?.(null);};
  useEffect(()=>{
    const element=canvas.current, context=element.getContext('2d');
    if(!context)return;
    let frame, visible=true, width=0,height=0, lastTime=0;
    const lookup=new Map(nodes.map(node=>[node.id,node]));
    const hoverScale=new Map();
    let expansion=scene.current.expanded?1:0;
    const wheel=event=>{event.preventDefault();const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?height:1);scene.current.targetZoom=Math.max(.5,Math.min(2.8,scene.current.targetZoom*Math.exp(-Math.max(-120,Math.min(120,delta))*.0015)));};
    element.addEventListener('wheel',wheel,{passive:false});
    const motion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const resize=new ResizeObserver(([entry])=>{width=entry.contentRect.width;height=entry.contentRect.height;const dpr=Math.min(window.devicePixelRatio||1,2);element.width=width*dpr;element.height=height*dpr;context.setTransform(dpr,0,0,dpr,0,0);});resize.observe(element);
    const visibility=()=>{visible=!document.hidden;};document.addEventListener('visibilitychange',visibility);
    const draw=time=>{
      frame=requestAnimationFrame(draw);if(!visible||!width)return;
      const s=scene.current, dt=Math.min(50,lastTime?time-lastTime:16.67);lastTime=time;const ease=motion?1:1-Math.exp(-dt/105);
      expansion+=((s.expanded?1:0)-expansion)*ease;
      for(const key of ['yaw','pitch','zoom'])s[key]+=(s['target'+key[0].toUpperCase()+key.slice(1)]-s[key])*ease;
      s.focus=s.focus.map((value,i)=>value+(s.targetFocus[i]-value)*ease);
      context.clearRect(0,0,width,height);
      const unit=Math.min(width/86,height/67), drift=motion?0:Math.sin(time/13000)*.012;
      const project=position=>{let [x,y,z]=position.map((v,i)=>v-s.focus[i]);const a=s.yaw+drift,b=s.pitch;const rx=x*Math.cos(a)+z*Math.sin(a),rz=-x*Math.sin(a)+z*Math.cos(a);const ry=y*Math.cos(b)-rz*Math.sin(b),depth=y*Math.sin(b)+rz*Math.cos(b);const scale=100/(100-depth);return {x:width*.5+rx*unit*scale*s.zoom,y:height*.46-ry*unit*scale*s.zoom,depth,scale};};
      const allowed=nodes.filter(node=>expansion>.015||node.level<2).slice(0,width<600?100:250);
      const points=allowed.map(node=>{const parent=lookup.get(node.parentId);const position=node.level>=2&&parent?node.position.map((v,i)=>parent.position[i]+(v-parent.position[i])*expansion):node.position;return {...node,...project(position),opacity:node.level>=2?expansion:1};});const projected=new Map(points.map(point=>[point.id,point]));
      const related=id=>id===s.active||lookup.get(id)?.parentId===s.active||lookup.get(s.active)?.parentId===id;
      points.forEach((point,index)=>{const parent=projected.get(point.parentId);if(!parent)return;const bright=related(point.id)||related(parent.id);context.strokeStyle=point.color;context.globalAlpha=(bright?.65:.32)*point.opacity;context.lineWidth=bright?1.5:.9;context.beginPath();context.moveTo(parent.x,parent.y);const cx=(parent.x+point.x)/2,cy=(parent.y+point.y)/2-12;context.quadraticCurveTo(cx,cy,point.x,point.y);context.stroke();
        if(!motion&&index%5===0&&point.status!=='locked'){const t=(time/(6500+index*47))%1;for(let trail=0;trail<4;trail++){const u=Math.max(0,t-trail*.014);context.globalAlpha=(.8-trail*.18)*point.opacity;context.beginPath();context.arc((1-u)**2*parent.x+2*(1-u)*u*cx+u*u*point.x,(1-u)**2*parent.y+2*(1-u)*u*cy+u*u*point.y,1.5-trail*.25,0,Math.PI*2);context.fillStyle=point.color;context.fill();}}
      });
      const labels=[];
      points.sort((a,b)=>a.depth-b.depth).forEach(point=>{const active=point.id===s.active,hover=point.id===s.hover;const dim=s.active&&!related(point.id);const locked=point.status==='locked';const pulse=motion||point.status==='completed'?1:1+Math.sin(time/1800+point.position[0])*.035;const current=hoverScale.get(point.id)||1;const smooth=current+((hover?1.14:1)-current)*ease;hoverScale.set(point.id,smooth);const radius=Math.max(point.level<2?6:3,point.size*point.scale*s.zoom)*pulse*smooth;point.radius=radius;context.globalAlpha=(locked?.22:dim?.4:Math.max(.65,Math.min(1,.88+point.depth/130)))*point.opacity;const glow=context.createRadialGradient(point.x,point.y,0,point.x,point.y,radius*2.8);glow.addColorStop(0,point.color);glow.addColorStop(.25,point.color);glow.addColorStop(1,'transparent');context.fillStyle=glow;context.beginPath();context.arc(point.x,point.y,radius*2.8,0,Math.PI*2);context.fill();const sphere=context.createRadialGradient(point.x-radius*.3,point.y-radius*.35,0,point.x,point.y,radius);sphere.addColorStop(0,'#ffffff');sphere.addColorStop(.35,point.color);sphere.addColorStop(1,'#343044');context.fillStyle=sphere;context.beginPath();context.arc(point.x,point.y,radius,0,Math.PI*2);context.fill();if(active||point.status==='completed'){context.strokeStyle=point.color;context.lineWidth=1;context.beginPath();context.arc(point.x,point.y,radius+5,0,Math.PI*2);context.stroke();}if(active||hover||point.level<2){const label=(point.label||'').slice(0,30)+((point.label||'').length>30?'…':'');context.font=(active?'600 ':'')+'12px system-ui';const w=context.measureText(label).width+16;const lx=Math.max(w/2+6,Math.min(width-w/2-6,point.x)),ly=point.y-radius-18;const box={x:lx-w/2,y:ly-10,w,h:23};const overlaps=labels.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y);if(active||hover||!overlaps){labels.push(box);context.globalAlpha=dim?.65:1;context.fillStyle='#10121ee8';context.beginPath();context.roundRect(box.x,box.y,w,23,5);context.fill();context.fillStyle='#eceaf4';context.textAlign='center';context.fillText(label,lx,ly+6);}}});
      context.globalAlpha=1;s.points=points;
    };frame=requestAnimationFrame(draw);
    return()=>{cancelAnimationFrame(frame);resize.disconnect();document.removeEventListener('visibilitychange',visibility);element.removeEventListener('wheel',wheel);};
  },[nodes]);
  const pick=(event)=>{const rect=canvas.current.getBoundingClientRect();return [...scene.current.points].reverse().find(p=>Math.hypot(p.x-(event.clientX-rect.left),p.y-(event.clientY-rect.top))<Math.max(16,p.radius+5));};
  const focus=node=>{const s=scene.current;s.active=node.id;s.targetFocus=node.position;s.targetZoom=1.55;setActiveId(node.id);onSelect?.(node);};
  return <div className="spatial-scene"><div className="spatial-tools"><button onClick={reset}>Reset view</button><button aria-label="Zoom in" onClick={()=>scene.current.targetZoom=Math.min(2.8,scene.current.targetZoom+.2)}>+</button><button aria-label="Zoom out" onClick={()=>scene.current.targetZoom=Math.max(.5,scene.current.targetZoom-.2)}>−</button><button onClick={()=>{scene.current.expanded=!expanded;setExpanded(!expanded);}}>{expanded?'Collapse':'Expand'}</button></div>
    <canvas ref={canvas} aria-label="Interactive 3D constellation. Drag to orbit and scroll or pinch to zoom. Use the node selector below to focus with a keyboard." onPointerDown={e=>{const s=scene.current;s.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});s.start={x:e.clientX,y:e.clientY};s.moved=false;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const s=scene.current,previous=s.pointers.get(e.pointerId);if(!previous){s.hover=pick(e)?.id;return;}if(s.pointers.size===2){const other=[...s.pointers.entries()].find(([id])=>id!==e.pointerId)[1];const before=Math.hypot(previous.x-other.x,previous.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>5)s.targetZoom=Math.max(.5,Math.min(2.8,s.targetZoom*after/before));s.moved=true;}else{s.targetYaw+=(e.clientX-previous.x)*.006;s.targetPitch=Math.max(-.65,Math.min(.8,s.targetPitch+(e.clientY-previous.y)*.006));if(Math.hypot(e.clientX-s.start.x,e.clientY-s.start.y)>5)s.moved=true;}s.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});}} onPointerUp={e=>{const s=scene.current;if(!s.moved){const node=pick(e);if(node)focus(node);}s.pointers.delete(e.pointerId);}} onPointerLeave={()=>{scene.current.hover=null;}} onPointerCancel={e=>{scene.current.pointers.delete(e.pointerId);scene.current.moved=true;}}/>
    <label className="spatial-select">Focus a node<select value={activeId} onChange={e=>{const node=nodes.find(node=>node.id===e.target.value);if(node)focus(node);else reset();}}><option value="">Whole constellation</option>{nodes.map(node=><option key={node.id} value={node.id}>{node.label}</option>)}</select></label>
  </div>;
}

const position=(index,level)=>{const a=index*2.399963;const radius=level===1?24+(index%4)*4:5+(index%5);return [Math.cos(a)*radius,Math.sin(a)*radius*.65,Math.sin(index*1.71)*16];};
export default function Constellation(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(null);
  useEffect(()=>{let alive=true;const load=()=>api('/constellation').then(value=>{if(alive){setData(previous=>JSON.stringify(previous)===JSON.stringify(value)?previous:value);setError('');}}).catch(e=>{if(alive)setError(e.message);});load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer);};},[]);
  const nodes=React.useMemo(()=>{if(!data)return [];const root={id:'root',label:'Your saved constellation',level:0,position:[0,0,0],size:12,color:'#cfbdfb',status:'active'};const output=[root];data.chats.forEach((chat,i)=>{const p=position(i,1),color=`hsl(${255+i*19%65} 65% 76%)`;output.push({id:chat.id,label:chat.title,content:'Captured conversation',level:1,parentId:root.id,position:p,size:6,color});data.messages.filter(message=>message.chat===chat.id).slice(-12).forEach((message,j)=>{const offset=position(j,2);output.push({id:message.id,label:message.content.slice(0,60),content:message.content,role:message.role,level:2,parentId:chat.id,position:p.map((v,k)=>v+offset[k]*(k===2?.4:1)),size:3,color});});});data.memories.forEach((memory,i)=>{const parent=output.find(node=>node.id===memory.source_chat_id)||root,p=parent===root?position(i+data.chats.length,1):parent.position.map((v,k)=>v+position(i+3,2)[k]*.7);output.push({id:memory.memory_id,label:memory.title,content:memory.summary,parentId:parent.id,level:parent===root?1:2,position:p,size:parent===root?6:3.5,color:parent.color,status:memory.sync_status==='SYNCED'?'completed':'default'});});return output;},[data]);
  return <section className="constellation-section"><div className="page-heading"><div><h1>Constellation</h1><p>Saved chats and memories, connected in space.</p></div></div><p className="muted">Turn on Save chat in a conversation to capture its messages here. Captured chat data stays on this device.</p>{error&&<p role="alert">{error}</p>}{!data?<p>Loading constellation…</p>:<><SpatialScene nodes={nodes} onSelect={setSelected}/>{nodes.length===1&&<p>No captured chats or memories yet. Start a conversation and turn on Save chat.</p>}{selected?.content&&<div className="constellation-inspector"><strong>{selected.role?`${selected.role==='user'?'You':'Assistant'} · `:''}{selected.label}</strong><p>{selected.content}</p></div>}<p className="muted">Drag to orbit · Scroll or pinch to zoom · Select a node to focus · {Math.max(0,nodes.length-1)} nodes</p></>}</section>;
}
