import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Brain,MessageSquare,Database,RefreshCw,Settings,Plus,ArrowUp,ArrowRight,Search,ShieldCheck,WifiOff,Wifi,Check,Clock,Archive,Trash2,PenLine,X,AlertTriangle,GitBranch,HardDrive,Sparkles,ChevronRight,BookOpen,Plug,Fingerprint,Menu} from 'lucide-react';
import {api,write,fields} from './api';
import Plugins from './Plugins';
import ChatWorkspace from './ChatWorkspace';
import MemoryMap from './MemoryMap';
import Constellation from './Constellation';
import Editor, {blankMemory as blank, memoryLengths} from './MemoryEditor';
import './style.css';
import './interface.css';
import './simple-ui.css';
import './theme.css';
import './space-theme.css';

const fmt=n=>n==null?'—':n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
const date=d=>d?new Date(d).toLocaleString(): 'Not yet';
const pageLabels = {'Constellation':'Constellation','Chat':'Chat','Memory Center':'Saved memories','Sync Center':'Device sync','Conflicts':'Changes to review','API Plugins':'AI connections','Settings':'Settings'};
const syncLabels = {LOCAL_ONLY:'This device only',PENDING:'Waiting to sync',SYNCING:'Syncing',SYNCED:'Synced',FAILED:'Will try again',CONFLICT:'Needs review',SUCCESS:'Synced',SUPERSEDED:'Replaced by a newer change'};
const connectionLabels = {ONLINE:'Connected',OFFLINE:'Not connected',NOT_CONFIGURED:'Not set up',CHECKING:'Checking connection',SYNCING:'Syncing',SYNC_FAILED:'Could not sync',SERVICE_UNAVAILABLE:'App unavailable'};
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
function Empty({icon:Icon=Database,title,children}){return <div className="empty"><Icon size={30}/><h3>{title}</h3><p>{children}</p></div>}
function App(){
 const [menuOpen,setMenuOpen]=useState(false);
 const [inference,setInference]=useState('configured');
 const [capture,setCapture]=useState(false),[captureBusy,setCaptureBusy]=useState(false);
 const toggleCapture=async enabled=>{setCaptureBusy(true);try{if(chatId)await write('/chats/'+chatId+'/capture',{enabled},'PUT');setCapture(enabled);await refresh();}catch(e){setError(e.message);}finally{setCaptureBusy(false);}};
 const [page,setPage]=useState(()=>new URLSearchParams(window.location.search).get('view')==='plugins'?'API Plugins':'Chat'),[status,setStatus]=useState({}),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [memories,setMemories]=useState([]),[sync,setSync]=useState({operations:[],conflicts:[]}),[chats,setChats]=useState([]),[messages,setMessages]=useState([]),[chatId,setChatId]=useState(null);
 const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[history,setHistory]=useState([]),[query,setQuery]=useState(''),[archived,setArchived]=useState(false),[prefs,setPrefs]=useState(null),[syncing,setSyncing]=useState(false);
 const filterRef=useRef({query,archived});filterRef.current={query,archived};const loadSequence=useRef(0);
 const refresh=async()=>{try{const [s,sy,c]=await Promise.all([api('/status'),api('/sync'),api('/chats')]);setStatus(s);setSync(sy);setChats(c)}catch(e){setStatus(s=>({...s,connection:'SERVICE_UNAVAILABLE'}));setError(e.message)}};
 const loadMemories=async()=>{const sequence=++loadSequence.current;const {query,archived}=filterRef.current;try{const result=await api('/memories?q='+encodeURIComponent(query)+'&archived='+archived);if(sequence===loadSequence.current&&query===filterRef.current.query&&archived===filterRef.current.archived)setMemories(result)}catch(e){setError(e.message)}};
 useEffect(()=>{refresh();api('/settings').then(setPrefs).catch(e=>setError(e.message));const timer=setInterval(refresh,10000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(page==='Memory Center')loadMemories()},[page,archived]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
 const act=async(fn,message)=>{try{await fn();if(message)setToast(message);await refresh();if(page==='Memory Center')await loadMemories()}catch(e){setError(e.message)}};
 const openChat=async id=>{pendingRequest.current=null;setInput('');try{setMessages(await api('/chats/'+id));setChatId(id);setCapture(chats.find(c=>c.id===id)?.capture||false);setPage('Chat')}catch(e){setError(e.message)}};
 const pendingRequest=useRef(null);
 const send=async e=>{e.preventDefault();if(!input.trim()||busy)return;const content=input;
 if(!pendingRequest.current||pendingRequest.current.content!==content){pendingRequest.current={content,chat_id:chatId,request_id:crypto.randomUUID(),capture};setMessages(ms=>[...ms,{role:'user',content,metadata:{}}]);}
 pendingRequest.current.inference=inference;
 setBusy(true);setError('');
 try{const result=await write('/chat',pendingRequest.current);setChatId(result.chat_id);setMessages(await api('/chats/'+result.chat_id));if(result.response){setInput('');pendingRequest.current=null;}if(result.warnings.length)setError(result.warnings.join(' '));await refresh();}
 catch(e){setError(e.message+' Your draft is kept. Send again to retry.');}finally{setBusy(false)}};
 const save=async value=>{if(editor?.resolve){await write('/conflicts/'+editor.resolve+'/resolve',{method:'MERGE',merged:value})}else if(editor?.memory_id){await write('/memories/'+editor.memory_id,{...value,expected_version:editor.version},'PUT')}else{await write('/memories',value)}setToast(editor?.memory_id?'Memory updated':'Memory saved');await refresh();await loadMemories()};
 const recommend=candidate=>setEditor({...candidate,review:true});
 const [mapMemories,setMapMemories]=useState([]);
 const detailRequest=useRef(0);
 const viewDetail=async m=>{const request=++detailRequest.current;setDetail(m);setHistory([]);setMapMemories([]);const [versions,all]=await Promise.all([api('/memories/'+m.memory_id+'/history'),api('/memories')]);if(request===detailRequest.current){setHistory(versions);setMapMemories(all)}};
 const startChat=()=>{pendingRequest.current=null;setChatId(null);setCapture(false);setMessages([]);setInput('');setPage('Chat');setError('')};
 const memoryGroups=Array.from(memories.reduce((groups,memory)=>{const key=memory.source_chat_id||'manual';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(memory);return groups;},new Map()),([id,items])=>({id,items,chat:chats.find(chat=>chat.id===id)}));
 const nav=[{name:'Chat',icon:MessageSquare},{name:'Memory Center',icon:BookOpen},{name:'Constellation',icon:Sparkles},{name:'Settings',icon:Settings}];
 const groups=[{title:'Workspace',items:nav.filter(item=>item.name!=='Settings')},{title:'Manage',items:[{name:'API Plugins',icon:Plug},{name:'Sync Center',icon:RefreshCw},{name:'Settings',icon:Settings}]}];
 useEffect(()=>{setMenuOpen(false)},[page,chatId]);
 return <div className="app simple-app"><aside id="app-sidebar" className={"sidebar "+(menuOpen?"menu-open":"")}>
 <a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Chat')}}><span className="brandmark"><Fingerprint size={26} strokeWidth={1.5}/></span>Vybe AI</a>
 <div className="workspace"><div>A little space to think</div></div>
 <button className="sidebar-new-chat" disabled={busy} onClick={startChat}><Plus size={18}/>New conversation</button>
 <nav aria-label="Main navigation">{groups.map(group=><div className="nav-group" key={group.title}><div className="nav-group-label">{group.title}</div>{group.items.map(({name,icon:Icon})=>{const selected=page===name||(name==='Sync Center'&&page==='Conflicts');return <button key={name} aria-label={pageLabels[name]} aria-current={selected?'page':undefined} className={selected?'selected':''} onClick={()=>{setPage(name);setMenuOpen(false);setError('')}}><Icon size={19}/>{pageLabels[name]}{name==='Sync Center'&&status.conflicts>0&&<span className="count amber">{status.conflicts}</span>}</button>})}</div>)}</nav>
 <div className="section-label recent-label">Recent chats</div><div className="recent">{chats.slice(0,8).map(c=><button key={c.id} disabled={busy} title={c.title} className={chatId===c.id?'active-chat':''} onClick={()=>openChat(c.id)}><MessageSquare size={15}/><span>{c.title}</span></button>)}{!chats.length&&<p>Your chats will appear here.</p>}</div>
 <div className="sidebar-foot"><HardDrive size={18}/><div><strong>Your personal workspace</strong><small>Chats saved on this device</small></div></div>
 </aside>
 <main><header><button className="mobile-menu icon" aria-label={menuOpen?"Close navigation":"Open navigation"} aria-expanded={menuOpen} aria-controls="app-sidebar" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={22}/></button><div className="breadcrumb"><span>Your workspace</span><ChevronRight size={14}/><strong>{pageLabels[page]}</strong></div><span className="header-note"><ShieldCheck size={15}/>{status.services ? `Local app ready · ${status.services.sync_scope === 'LOCAL' ? 'Local sync server' : 'Remote sync'} · AI: ${status.services.ai_last_route === 'NOT_TESTED' ? 'not tested yet' : status.services.ai_last_route}` : 'Connecting to local app…'}</span></header>
 <div className="content">{error&&<div role="alert" className="error global-error"><AlertTriangle size={17}/><span>{error}</span><button className="icon" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {page==='Chat'&&<ChatWorkspace inference={inference} onInference={setInference} capture={capture} captureBusy={captureBusy} onCapture={toggleCapture} messages={messages} input={input} setInput={setInput} busy={busy} status={status} prefs={prefs} onSend={send} onNewChat={startChat} onNavigate={setPage} onReview={(candidate,related)=>act(async()=>{if(related){const all=await api('/memories');const found=all.find(x=>x.memory_id===related);recommend(found?{...found,...candidate,local_only:found.local_only}:candidate)}else recommend(candidate)})} onDismiss={message=>act(async()=>{await api('/messages/'+message.id+'/candidate',{method:'DELETE'});setMessages(await api('/chats/'+chatId))},'Suggestion dismissed')}/>}
 {page==='Constellation'&&<Constellation/>}
 {page==='Memory Center'&&<>
 <div className="page-heading"><div><h1>Saved memories</h1><p>Things you want the assistant to remember for your next chat.</p></div><button className="primary" onClick={()=>setEditor({...blank,memory_type:prefs?.preferences.default_type||'STANDARD'})}><Plus size={17}/>New memory</button></div>
 <div className="memory-explainer"><BookOpen size={21}/><p>Save preferences, plans, or useful details here. You can change or remove them anytime.</p></div>
 <div className="toolbar"><form className="search" onSubmit={e=>{e.preventDefault();loadMemories()}}><Search size={18}/><input aria-label="Search memories" placeholder="Find a saved detail…" value={query} onChange={e=>setQuery(e.target.value)}/><button>Search</button></form><button className={archived?'selected':''} onClick={()=>{setQuery('');setArchived(!archived)}}><Archive size={17}/>{archived?'Back to saved memories':'Archived memories'}</button></div>
 {archived&&<p className="muted">Archived memories are kept here but are not used in replies. Choose Restore to use one again.</p>}
 <div className="memory-chat-groups">{memoryGroups.map(group=><section className="memory-chat-group" key={group.id}><div className="memory-chat-heading"><div><h2><MessageSquare size={18}/>{group.id==='manual'?'Added manually':group.chat?.title||'Conversation from another device'}</h2><span>{group.items.length} saved {group.items.length===1?'memory':'memories'}</span></div>{group.chat&&<button onClick={()=>openChat(group.id)}>Open chat<ArrowRight size={15}/></button>}</div><div className="memory-grid">{group.items.map(m=><article className="memory-card" key={m.memory_id}>
 <div className="row"><Badge tone={m.sync_status==='CONFLICT'?'amber':'neutral'}>{syncLabels[m.sync_status]||'Saved'}</Badge></div>
 <h3><button className="plain" onClick={()=>act(()=>viewDetail(m))}>{m.title}</button></h3><p>{m.summary}</p>
 <div className="tags">{m.tags.map(t=><span key={t}>{t}</span>)}</div><div className="memory-meta">Updated {new Date(m.updated_at).toLocaleDateString()}</div>
 <div className="card-actions"><button onClick={()=>setEditor(m)}><PenLine size={15}/>Edit</button><button onClick={()=>act(()=>write('/memories/'+m.memory_id,{...fields(m),archived:!m.archived,memory_type:m.memory_type==='ARCHIVE_ONLY'?'STANDARD':m.memory_type,expected_version:m.version},'PUT'),'Memory updated')}><Archive size={15}/>{archived?'Restore':'Archive'}</button><button aria-label={'Delete '+m.title} onClick={()=>{if(confirm('Delete this memory? This also removes it from your synced devices.'))act(()=>api('/memories/'+m.memory_id+'?expected_version='+m.version,{method:'DELETE'}),'Memory deleted')}}><Trash2 size={15}/></button></div>
 </article>)}</div></section>)}</div>
 {memories.length===0&&<Empty icon={BookOpen} title={query?'No memories found':archived?'No archived memories':'Nothing saved yet'}>{query?'Try a different word or clear your search.':archived?'Memories you archive will appear here.':'Choose New memory to add a detail, or save a suggestion during a chat.'}</Empty>}
 </>}
 {(page==='Sync Center'||page==='Conflicts')&&<>
 <button className="back-link" onClick={()=>setPage('Settings')}>← Back to Settings</button>
 <div className="page-heading"><div><h1>{pageLabels[page]}</h1><p>{page==='Conflicts'?'A memory was changed in two places. Choose the version you want to keep.':'Keep saved memories up to date on your connected devices.'}</p></div><button className="primary" disabled={syncing||status.connection==='NOT_CONFIGURED'} onClick={()=>act(async()=>{setSyncing(true);try{await write('/sync',{})}finally{setSyncing(false)}},'Sync check finished')}><RefreshCw size={17}/>{syncing?'Syncing…':'Sync now'}</button></div>
 {page==='Sync Center'&&<><section className="panel sync-summary"><h2>{connectionLabels[status.connection]||'Checking connection'}</h2><p>{status.connection==='NOT_CONFIGURED'?'Device sync has not been set up. You can still chat and save memories on this device.':status.connection==='ONLINE'?'Your sync service is connected. Changes are sent automatically.':'Your saved memories are still on this device. Sync will try again when the service is available.'}</p><div className="sync-summary-row"><span><strong>{status.pending||0}</strong> changes waiting</span><span>Last synced: {date(status.last_sync)}</span></div>{status.conflicts>0&&<button onClick={()=>setPage('Conflicts')}><AlertTriangle size={17}/>Review changes<span className="badge amber">{status.conflicts}</span></button>}</section></>}
 {sync.conflicts.map(c=><section className="conflict" key={c.conflict_id}><h3>Which version would you like to keep?</h3><div className="two">{[['On this device',c.local],['On your other device',c.remote]].map(([label,m])=><div className="conflict-version" key={label}><small>{label}</small><h4>{m?.title||'Not available'}</h4><p>{m?.summary}</p>{m?.deleted_at&&<Badge tone="amber">Deleted</Badge>}</div>)}</div><div className="actions"><button onClick={()=>act(()=>write('/conflicts/'+c.conflict_id+'/resolve',{method:'LOCAL'}),'Kept the version from this device')}>Keep this device’s version</button><button disabled={!c.remote} onClick={()=>act(()=>write('/conflicts/'+c.conflict_id+'/resolve',{method:'REMOTE'}),'Kept the version from your other device')}>Keep the other version</button><button className="primary" onClick={()=>setEditor({...c.local,resolve:c.conflict_id,summary:c.local.summary+'\n\n'+(c.remote?.summary||'')})}>Combine and edit</button></div></section>)}
 {page==='Conflicts'&&sync.conflicts.length===0&&<Empty icon={ShieldCheck} title="Nothing to review">Your saved memories have no competing changes.</Empty>}
 {page==='Sync Center'&&<details className="simple-disclosure technical-details"><summary>Technical details</summary><p>Connection: {status.connection} · Failed attempts: {status.failed||0} · Synced memories at last check: {status.cloud_memories??'Not available'}</p><h3>Sync history</h3>{sync.operations.length===0?<p>No sync activity yet.</p>:<div className="table-wrap"><table><thead><tr><th>Operation</th><th>Memory</th><th>Status</th><th>Retries</th></tr></thead><tbody>{sync.operations.map(o=><tr key={o.id}><td>{o.id.slice(0,8)}</td><td>{o.entity.slice(0,8)}</td><td><Badge tone={o.status==='FAILED'?'amber':'neutral'}>{syncLabels[o.status]||o.status}</Badge>{o.error&&<small>{o.error}</small>}</td><td>{o.retries}</td></tr>)}</tbody></table></div>}</details>}
 </>}
 {page==='API Plugins'&&<Plugins onChanged={refresh} onBack={()=>setPage('Chat')}/>}
 {page==='Settings'&&<>
 <div className="page-heading"><div><h1>Settings</h1><p>A few options to make the assistant work for you.</p></div></div>
 {prefs&&<div className="settings-grid">
 <section className="panel"><h2>Remember useful details</h2><p>The assistant can suggest things to remember after a chat. You always review them before saving.</p><label className="check"><input type="checkbox" checked={prefs.preferences.memory_enabled} onChange={e=>{const next={...prefs.preferences,memory_enabled:e.target.checked};act(async()=>{await write('/settings',next,'PUT');setPrefs({...prefs,preferences:next})},'Settings saved')}}/>Suggest memories after conversations</label></section>
 <section className="panel settings-action"><div><h2>AI connections <span className="optional-label">Optional</span></h2><p>Connect an AI service you already use. You can keep chatting without adding one.</p></div><button onClick={()=>setPage('API Plugins')}>Manage AI connections<ArrowRight size={17}/></button></section>
 <section className="panel settings-action"><div><h2>Device sync</h2><p>See whether your saved memories are up to date across connected devices.</p>{status.conflicts>0&&<p className="review-note">{status.conflicts} {status.conflicts===1?'memory needs':'memories need'} your review.</p>}</div><button onClick={()=>setPage('Sync Center')}>View sync status<ArrowRight size={17}/></button></section>
 <section className="panel"><h2>Your saved information</h2><p>Your chats and memories are saved on this device. You can edit, archive, or delete memories from Saved memories.</p><p>If you choose a connected AI service, your messages and relevant memories may be sent to it. Memories marked “Keep on this device only” stay here and use the assistant on this device.</p><button onClick={()=>setPage('Memory Center')}>View saved memories<ArrowRight size={17}/></button></section>
 <details className="simple-disclosure technical-details"><summary>Advanced settings</summary><label>Default memory length<select value={prefs.preferences.default_type} onChange={e=>{const next={...prefs.preferences,default_type:e.target.value};act(async()=>{await write('/settings',next,'PUT');setPrefs({...prefs,preferences:next})},'Settings saved')}}>{Object.entries(memoryLengths).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 <div className="setting-row"><span>Embedding model</span><b>{prefs.embedding_model}</b></div><div className="setting-row"><span>Vector engine</span><b>Qdrant Edge · {status.vector_ready?'Ready':'Setup needed'}</b></div><div className="setting-row"><span>Local model</span><b>{prefs.local_model}</b></div><div className="setting-row"><span>Cloud model</span><b>{prefs.cloud_model}</b></div><div className="setting-row"><span>Memory text / vector storage</span><b>{fmt(status.compact_bytes)} / {fmt(status.vector_bytes)}</b></div><p>Local model and sync service addresses are configured in the backend .env file. Model availability is checked when you send a message.</p><small>Device ID: {status.device_id}</small>
 </details></div>}
 </>}
 </div><footer><span>Chats are saved on this device.</span><span>Vybe AI</span></footer></main>
 {editor&&<Editor value={editor} heading={editor.resolve?'Combine changes':editor.memory_id?'Edit memory':'Save a memory'} onClose={()=>setEditor(null)} onSave={save}/>}{detail&&<div className="overlay" onClick={()=>setDetail(null)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="row"><h2>{detail.title}</h2><button className="icon" aria-label="Close details" onClick={()=>setDetail(null)}><X/></button></div><p>{detail.summary}</p><MemoryMap selected={detail} memories={mapMemories} onSelect={memory=>act(()=>viewDetail(memory))}/><h3>Where this came from</h3>{detail.source_chat_id?<button onClick={()=>{setDetail(null);openChat(detail.source_chat_id)}}><MessageSquare size={15}/>Open source conversation</button>:<p className="muted">You added this memory</p>}<details className="simple-disclosure"><summary>Previous versions</summary><div className="timeline">{history.map((h,i)=><div key={i}><Badge>Version {h.version}</Badge><small>{date(h.updated_at)}</small><p>{h.summary}</p></div>)}</div></details></section></div>}{toast&&<div role="status" className="toast"><Check size={17}/>{toast}</div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
